name: Click-to-Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Install required packages
        run: |
          sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python
          sudo apt-get install python-is-python3
          sudo apt-get install python-devel
      
      - name: Install bazel
        run: |
          wget https://github.com/bazelbuild/bazel/releases/download/0.13.0/bazel-0.13.0-installer-linux-x86_64.sh
          chmod +x bazel-0.13.0-installer-linux-x86_64.sh
          ./bazel-0.13.0-installer-linux-x86_64.sh --user
          echo 'export PATH="$PATH:$HOME/bin' >> ~/.bashrc

      - name: Clone repo runtimes common
        run: |
          git clone https://github.com/GoogleCloudPlatform/runtimes-common.git
          curl -LO https://storage.googleapis.com/idiff/v0.1.0/iDiff-linux-amd64 && mv iDiff-linux-amd64 iDiff && chmod +x iDiff && sudo mv iDiff /usr/local/bin/
      - name: Build gazelle
        run: |
          cd runtimes-common
          bazel run //:gazelle