name: Click-to-Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Install required packages
        run: |
          sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python
      
      - name: Install bazel
        run: |
          wget https://github.com/bazelbuild/bazel/releases/download/0.19.1/bazel-0.19.1-installer-linux-x86_64.sh
          chmod +x bazel-0.19.1-installer-linux-x86_64.sh
          ./bazel-0.19.1-installer-linux-x86_64.sh --user
          echo 'export PATH="$PATH:$HOME/bin' >> ~/.bashrc

      - name: Clone repo runtimes common
        run: |
          git clone https://github.com/GoogleCloudPlatform/runtimes-common.git
          cd runtimes-common

      - name: Build gazelle
        run: |
          cd runtimes-common
          bazel run //:gazelle